language: go

go:
  - '1.9'
  - '1.10'
  - tip

cache:
  directories:
    - vendor

services:
  - postgresql

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

before_script:
  - psql -U postgres -c 'CREATE DATABASE go_restful;';

script:
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage-all.out -service=travis-ci
